### ISSUE TITLE
Strip "[MP]" prefix for `topic:multiplayer` PRs

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-interactive-changelog#10]
![image](https://github.com/godotengine/godot-interactive-changelog/assets/4701338/c1dad852-4b3a-422b-a1e3-2c36ba29fcce)

Possibly depends on doing #8 first, and then treating `MP` as a known prefix for `topic:multiplayer`.

**Comment by YuriSizov** [comment]
I implemented this without checking for labels for now, for simplicity. I don't expect there to be collisions.
