### ISSUE TITLE
Bug: Create Folder in Godot Android 

### ISSUE THREAD

**Issue by O-C19E** [godotengine/godot-interactive-changelog#14]
When Creating a new project, after we select "Create Folder" and we don't name the folder instead we touch anywhere except the keypad, this should result in cancellation of the folder naming process, but instead the game freezes, this doesn't only happen when we create a new project, but every time we create a new folder. The only way to unfreeze it is to restart the engine

**Comment by akien-mga** [comment]
This issue tracker is for the interactive changelog website.

You seem to want to report a bug with the Godot editor, this should go there: https://github.com/godotengine/godot/issues/
