### ISSUE TITLE
Add button to copy markdown changelog

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-interactive-changelog#2]
In the markdown view:

![image](https://github.com/godotengine/godot-interactive-changelog/assets/4701338/b13954d3-35a7-421e-ae03-d1644512710b)

When using this as a base for a blog post, I usually copy the contents to a local file to edit. It would be nice to have a button to copy the whole text area, or support Ctrl+A when it has focus.

**Comment by YuriSizov** [comment]
This was implemented in https://github.com/godotengine/godot-interactive-changelog/commit/991a38b066f885c94bbb69e0ebf61eac14de6f98.
