### ISSUE TITLE
Remove dot at the end of a PR title before adding the "(GH-#)." suffix

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-interactive-changelog#4]
Some contributors write their PR titles with a dot at the end. It's fine, but since it's not done consistently, and it would be a bit overkill for us to edit all PR titles to remove trailing dots, I would suggest doing it as a post-processing step.

![image](https://github.com/godotengine/godot-interactive-changelog/assets/4701338/790b3f38-d150-498b-9f6c-fa0212e9f5a6)

We can just remove the dot at the end before appending the "(GH-#)." suffix, unless it's "..." which we should likely keep as is.

Not sure about ".." which is something folks like reduz tend to use, we can assume this won't really happen and would be fixed by editing the PR itself.

**Comment by YuriSizov** [comment]
I can't recall PRs ending with `..` or `...`, why would that be the case? Should probably strip that completely. If it's from a commit message that is too long, then we should probably edit it ahead of generating the log.

**Comment by akien-mga** [comment]
I could imagine some passive aggressive commit message like "Thank you X11 for such a delightfully designed APi..." but well :P

Realistically, no, it's unlikely to be a common occurrence and stripping all dots probably won't harm much if such dramatic ellipsis ever happens.
