### ISSUE TITLE
Reformat existing "[Context]" prefixes in PR titles to "Context:"

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-interactive-changelog#8]
Some contributors add a contextualizing prefix to their PRs of the form `[Context]`, e.g.:
```
[TextEdit] Expose all auto-wrap modes.
```
or
```
[RTL] Fix multithreaded resizing.
```

To ensure consistency, I'm used to change those to "TextEdit:" or "RTL:", so once formatted with the "GUI:" prefix inferred from their label (and removing the dot from #4), they would be:
```
GUI: TextEdit: Expose all auto-wrap modes (GH-74813).
```
or
```
GUI: RTL: Fix multithreaded resizing (GH-78241).
```

**Comment by YuriSizov** [comment]
Done, also included more exotic variants using single quotes and backticks, because we have those. `[ci/web]` is not converted at the moment, not sure if it should be replaced with a special rule to capitalize it properly, or replace it, or maybe even drop it.

**Comment by akien-mga** [comment]
I think some rare occurences like `[ci/web]` going through the cracks is ok, better leave some cases unoptimized rathan than make the logic too convoluted.
